### ISSUE TITLE
Remplir manuellement `inst/translation_iucn.csv`

### ISSUE THREAD

**Issue by ALanguillaume** [inrae/diades.atlas#100]
Il était initialement prévu de monter en base les traductions des catégories UICN. Pour gagner du temps il serait préférable de compléter manuellement le fichier csv `inst/translation_iucn.csv` avec les langues manquantes (Espagnol et Portugais).

- [ ] Compléter les traductions pour l'Espagnol et le Portugais dans `inst/translation_iucn.csv` @PMHLambert 
- [ ] Mettre à jour la vignette de traducion @ALanguillaume

**Comment by ALanguillaume** [comment]
@PMHLambert Voici le fichier à remplir.
[translation_iucn.csv](https://github.com/inrae/diades.atlas/files/8528605/translation_iucn.csv)

Il suffit pour toi de le compléter et de le redéposer la nouvelle version dans cette discussion.
Je me chargerai de faire la Pull Request pour mettre l'application à jour.

**Comment by PMHLambert** [comment]
Voilà les traductions des statuts iucn
[translation_iucn.csv](https://github.com/inrae/diades.atlas/files/8553296/translation_iucn.csv)

**Comment by statnmap** [comment]
Merci. Inclu dans https://github.com/inrae/diades.atlas/pull/113
