### ISSUE TITLE
Presentation - Slides for the conference

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#110]
- 3 slides about how ThinkR work and what we did for DiadES

**Comment by statnmap** [comment]
les slides de la prez: /mnt/Data/ThinkR/Gitlab_Forge/ThinkR/Commercial/demarche.propre.thinkr/04-workflow-devops-package-short-prez.pdf

**Comment by PMHLambert** [comment]
Fisrt draft of the presentation of the IWA. You can add your slides aroud slide 
[WP7_IWA_Lambert.pptx](https://github.com/inrae/diades.atlas/files/8878756/WP7_IWA_Lambert.pptx)

**Comment by PMHLambert** [comment]
parfait à ce stade. Avec les sources je dois pouvoir faire des images à intégrer dans ma présentation ?

**Comment by statnmap** [comment]
Voici les sources:  

[04-workflow-devops-package-short-prez.zip](https://github.com/inrae/diades.atlas/files/8897654/04-workflow-devops-package-short-prez.zip)

- ![baka_rstudio](https://user-images.githubusercontent.com/21193866/173523950-7f0d5a24-47e9-4a1e-988e-fb4608255096.png)
- ![tous_hex](https://user-images.githubusercontent.com/21193866/173523971-8abce6b0-be38-447a-a62c-d5c2c9d6fd5f.png)
- ![diades_pkgdown](https://user-images.githubusercontent.com/21193866/173524070-2e217203-9676-41c8-9fff-d84c2d0e23d0.png)
- ![buzzleclair](https://user-images.githubusercontent.com/21193866/173524016-afe72dee-ed5f-4c04-a437-ddf2f55df2e8.jpg)
- ![diades_home_en](https://user-images.githubusercontent.com/21193866/173524100-3af1d582-e5e6-46f6-a4cd-5a161f94c6f6.png)

**Comment by statnmap** [comment]
Validé en réunion 9/02/2023
