### ISSUE TITLE
bulles d'aide

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#111]
On aurait besoin d'ajouter sur l'onglet 2 des bulles d'aide au niveau

 - [x]    choisir une étude de cas,
 - [x]    choisir un service écosystémiques,
 - [x]    montrer les résultats

- [x] Peux-on rajouter facilement des bulles dans les titres de chaque onglet ?

- [x] Peut-on insérer des liens hypertextes dans les bulles ? => Oui avec markdown

- [x] Peut-on élargir les bulles pour faciliter la lecture ? => Pas facilement.

**Comment by statnmap** [comment]
J'ajoute @ALanguillaume parce qu'on est en train de se séparer du Google Sheet sur demande de Eric...
Ceci dit, je pense que vous pouvez quand même écrire sur le Google sheet, on pourra récupérer ensuite.
Je laisse Antoine confirmer ou bien vous envoyer des csv séparés dans une issue dédiée.

On peut ajouter des nouvelles bulles sur des boutons. Je dois vérifier comment ça fonctionne pour des titres.
Rien de vous empêche d'anticiper que ça marchera en ajoutant une ligne au fichier de traduction, en lui donnant un nom explicite et different du reste.

Le format de rédaction est le markdown. Donc vous pouvez mettre en forme avec la syntaxe markdown. Ce qui inclut les liens hypertexte.
C'est la même syntaxe que pour les issue GitHub: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Pour la largeur, j'ai déjà commencé à le traiter, mais je peux difficilement agrandir de trop sinon ça sort de la page.
J'ai mis ça de côté pour le moment.

J'ajoute ces réponses à l'issue que tu as ouverte pour la suite des discussions: https://github.com/inrae/diades.atlas/issues/111

**Comment by statnmap** [comment]
Pour élargir les bulles, je propose que toutes les bulles fassent la largeur de l'écran (avec une marges).  
De cette façon, on est sûrs que ça ne dépasse pas et le texte devient plus lisible.   
Si vous validez, on envoie !

Voilà ce que ça rend, selon la position du bouton d'aide

- a gauche: choisir une espece
![image](https://user-images.githubusercontent.com/21193866/166442458-71b3834e-60ce-48bb-8584-12ac7bf4dc56.png)


- au milieu : changer la résolution
![image](https://user-images.githubusercontent.com/21193866/166442552-1080b18b-0a76-41db-86d1-b85198b9246c.png)


- a droite: statut de conservation
![image](https://user-images.githubusercontent.com/21193866/166442595-5aec8422-8481-4540-b3c2-d31e128ebd84.png)

**Comment by statnmap** [comment]
Est-ce que cette nouvelle apparence vous convient ?

**Comment by statnmap** [comment]
Ok. Vu le 14 juin en réunion
