### ISSUE TITLE
Ajouter le numéro de version dans le bas de page

### ISSUE THREAD

**Issue by equinton** [inrae/diades.atlas#112]
Il serait intéressant de rajouter le numéro de version de l'application et de la base de données dans le bas de page (bandeau contenant le logo) : cela permettrait de mieux savoir où on en est.

Pour la base de données, je vais rajouter une table dbversion (dbversion_id, dbversion_number, dbversion_date), avec l'info à récupérer ainsi : 
~~~
select dbversion_number, dbversion_date from diadesatlas.dbversion order by dbversion_date desc limit 1;
~~~

**Comment by statnmap** [comment]
Merci de valider que les numéros de version apparaissent bien dans le footer de l'application (prochain release)

**Comment by statnmap** [comment]
Vu et validé en réunion le 14 juin
