### ISSUE TITLE
Vérifier pourquoi les données sont en doubles dans `extendedNit`

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#122]

**Comment by PMHLambert** [comment]
Le problème provenait d'un changement de nommage des fichiers de sortie du modèle. Les simulations ont été relancées, les résultats ont été rechargés dans les bases de données et un dump a été déposé sur gitlab

**Comment by statnmap** [comment]
Corrigé dans la database 2022-05-20
