### ISSUE TITLE
Exploration of models RData files

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#13]
Models outputs are stored as lists in a RData file.  
Explore how it is possible to transform it as a rectangular table or how easy it is to extract information for graphs and maps.

**Comment by PMHLambert** [comment]
An example of model output is in results_Alosa.rds (file type not supported in github). I detected a missing that will be soon fixed.
The conversion to a csv file is done by R script using annex tables
[exampleModelOutput.zip](https://github.com/inrae/diades.atlas/files/5574309/exampleModelOutput.zip)

**Comment by statnmap** [comment]
There is a R Script for rewriting list data
- These reformated flat data will be in the database.
- On the other hand, simulations made online will be processed with the R script to be flattened. These simulations will be temporary, deleted after closing the application.

**Comment by statnmap** [comment]
Predictions of the model are in the database, under table "hybrid_model_result" in a tidy format. 
Verified during meeting 2021-07-22.
