### ISSUE TITLE
pb de simulation pour Chelon ramada.

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#137]
quand on lance l'appli, la simulation est correcte pour Alosa alosa mais n'aboutit pas pour Chelon ramada.
En exécutant pas à pas be-page4-future.Rmd pour Chelon ramada, 

En faisant un debugonce sur (runSimulation) j'obtiens un message d'erreur
Erreur dans (function (cond)  : 
  erreur d'ï¿½valuation de l'argument 'x' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'as.matrix' : Failed to fetch row: ERREUR:  valeur en dehors des limites : trop petit
au niveau de la ligne 241

**Comment by PMHLambert** [comment]
en déplaçant le collect() avant la série de mutate (vers la ligne 218), le pb semble résolu mais je ne comprends pourquoi... Je laisse les spécialistes vérifier

**Comment by PMHLambert** [comment]
j'ai poussé sur la branche patrick-simu

**Comment by statnmap** [comment]
La simulation marche. Validé le 9/02/2023
