### ISSUE TITLE
Run the Shiny app locally without Mongo

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#141]
You can run the Shiny Application, provided that you set the access to the database correctly

Si tu suis bien les instructions du Readme:

- Retrieve package and develop (Que tu as dû déjà faire en partie): https://github.com/inrae/diades.atlas#retrieve-package-and-develop
- Test the application locally: https://github.com/inrae/diades.atlas#test-the-application-locally
- Backend requirement > ## PostGis: https://github.com/inrae/diades.atlas#postgis

**Comment by statnmap** [comment]
Merci de valider que l'application Shiny se lance en local sans erreur.

**Comment by PMHLambert** [comment]
Désolé je n'ai pas réussi

Je pense que je bloque à l'instruction
docker run --name=mongo --rm -p 2811:27017 -e MONGO_INITDB_ROOT_USERNAME=Colin -e MONGO_INITDB_ROOT_PASSWORD=AsAboveSoBelow789123 mongo:4.0
J'ai l'impression qu'il attend quelque chose qui ne vient pas
2022-06-18T14:04:19.046+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
J'ai remplacé Colin par patrick.lambert au cas où.... Pas de changement
Logiquement dans R
en lançant 
golem::run_dev()
j'obtiens une message d'erreur
ℹ Loading diades.atlas
Writing NAMESPACE
Writing NAMESPACE
ℹ Loading diades.atlas
 Erreur dans value[[3L]](cond) : 
MongoDB has not been started or does not exist

mais comme je ne comprends pas vraiment ce que je fais, ce n'est pas surprenant que cela ne marche pas !

**Comment by PMHLambert** [comment]
cela pourrait venir golem-config.yml en regardant les différences avant commit
   golem_version: 0.0.0.9000
   app_prod: no
   POSTGRES_DBNAME: diades
-  POSTGRES_HOST: localhost
+  POSTGRES_HOST: citerne.bordeaux.irstea.priv
   POSTGRES_PORT: '5432'
   mongocollection: cache
   mongourl: mongodiades
   mongoport: '27017'
-  mongodb: 'diadescache'
+  mongodb: diadescache
 production:
   app_prod: yes
 dev:
-  golem_wd: !expr here::here()
+  golem_wd: /home/patrick/Documents/workspace_diadesatlas/diades.atlas
   mongourl: 127.0.0.1
   mongoport: '2811'
les ' ' me parraissent suspectes

**Comment by PMHLambert** [comment]
je progresse mais ce n'est pas encore cela ...

MongoDB has not been started or does not exist
Using local RAM memory for this session
 Erreur : la connexion au serveur sur « citerne.bordeaux.irstea.priv » (10.33.192.25), port 5432 a échoué : FATAL: authentification LDAP échouée pour l'utilisateur « diadesatlas_owner »
la connexion au serveur sur « citerne.bordeaux.irstea.priv » (10.33.192.25), port 5432 a échoué : FATAL: authentification LDAP échouée pour l'utilisateur « diadesatlas_owner »

dans .Renviron j'ai bien le bon POSTGRES_USER et le bon POSTGRES_PASS.
Je cerche ailleurs???

**Comment by statnmap** [comment]
Validé en réunion le 9/02/2023
