### ISSUE TITLE
I'd like a footer with links

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#149]
I need to acknowledges for Diades and show the source code

## Validation

- [ ] The image of DiadeS in the footer can be click and opens https://diades.eu
- [ ] There is a link to the GitHub repository in the footer of the app

## Technicals

https://github.com/inrae/diades.atlas/blob/c5590d581da0a804bc23901658f2b9274b56988c/inst/app/www/footer.html

En théorie
```html
<a href="https://diades.eu"><img src="www/DiadES.jpg" height="30px" /></a>
```

**Comment by PMHLambert** [comment]
It works but open two pages on a single click

**Comment by PMHLambert** [comment]
new link to the DiadES web site added
