### ISSUE TITLE
[4 - Future] - Fonctions métier

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#19]
consider several mortatlity cursors per country (to regionalise a little more the anthropogenic pressure), or even cursors for 2 or 3 periods (to keep track of trends in management). IRisk to lose  simplicity in the interactivity and therefore in the effectiveness of the message.

ThinkR:

- [x] Permettre une seconde entrée pour les mortalités (Avant 2050, Après 2050)
- [x] En sortie, on reprend la meme chose que "Changement Climatique"
- [x] Explorer les scripts fournis: diades.atlas.data
- [x] Première version de la fonction qui lance une simulation HyDiaD. Nécessite probablement encore de l'optimisation
[HyDiaDsimulation.zip](https://github.com/inrae/diades.atlas/files/8332166/HyDiaDsimulation.zip)
- [x] Implémenter la vignette adéquate et les fonctions
- [x] Implémenter les tests unitaires
- [x] Ajouter à l'interface

**Comment by statnmap** [comment]
- Separate visually parameters from predictions
- Define all parameters needed => Add info in issue #23 
![image](https://user-images.githubusercontent.com/21193866/102232519-84242800-3eef-11eb-818e-91cd411adb18.png)

**Comment by statnmap** [comment]
On pourra voir si on peut faire les prédictions directement dans la base

**Comment by ColinFay** [comment]
@PMHLambert nous n'avons pas le code permettant de calculer les prédictions, est-ce qu'ils sont disponibles ?

**Comment by statnmap** [comment]
Les données et scripts sont dans: diades.atlas.data

**Comment by statnmap** [comment]
Exploration du jour sur les scripts modèle  

> Le code est toujours en cours de développement, mais je met mes observations ici au fur et à mesure pour ne pas les perdre

- Reprise du code tel quel, sans essayer d'optimiser ou de vérifier s'il est correct
- Modifications lorsque nécessaire pour que les fonctions marchent avec la base de données le plus loin possible
- Séparation des fonctions dans les fonctions: 
  - identification des paramètres non déclarés dans la fonction: cela fonctionne avant séparation car les variables sont utilisées comme variables globales, mais il vaut mieux tout déclarer. En sortant la fonction, on se rend compte plus vite des variables manquantes.
- Pas de moyen de vérifier que les calculs matriciels sont corrects.
    + Le code fait appel a plusieurs calculc matriciels ou entre vecteurs. Ils sont de la même taille et supposés correspondre aux bons bassins versants / années. Pour cela, le code `arrange()` les variables par ordre alphabétique. Mais cela ne garantit pas une correspondance parfaite. Le mieux est de passer par des `data.frame` autant que possible de façon à faire des jointures sur la base d'une colonne commune. 
    + J'ai réalisé cette opération pour le calcul avec `spawnersTo_50` parce qu'ils étaient créés trop loin dans le code pour être sûr qu'ils correspondaient. Ci dessus le code modifié. Ici, on passe de `data.frame` à `matrix` et inversement, mais en théorie on devrait pouvoir tout faire en `data.frame`, à condition de le faire depuis le début.
    + Il y a peu de raison qu'il y ait des erreurs d'appairage, mais ce n'est pas garanti dans le code original


```r
# catchment_spawnersTo_50 est une table créé au départ à la place de `spawnersTo_50` pour conserver le nom des BV
# > catchment_spawnersTo_50
# Source:     lazy query [?? x 3]
# Database:   postgres
#   [diadesatlas_owner@localhost:5432/diades]
# Ordered by: basin_name
   basin_name surface_area
   <chr>             <dbl>
 1 Authie             1305
 2 Orkla              3092
 3 Vefsna             4122
 4 Aulne              1495

  # survival offspring
  if (parameter$withAllee) {
    # => Safe version: Join Spawners to be sure that basins are in the same order
    catchment_spawnersTo_50_collect <- catchment_spawnersTo_50 %>% collect()
    # Keep in order of `spawnersTo`
    survivalOffsprings <- as.data.frame(spawnersTo) %>% 
      # get back rownames as column for the join
      rownames_to_column(var = "basin_name") %>% # count() # 134
      rename(spawnersTo = V1) %>% 
      # Join
      left_join(catchment_spawnersTo_50_collect, by = "basin_name") %>% # %>% count()
      # Calculate survivalOffsprings with correct basin
      mutate(
        survivalOffsprings = parameter$r * 
          (spawnersTo^2 / (spawnersTo_50^2 + spawnersTo^2)) * spawnersTo) %>% 
      # Back to matrix for the calculations
      column_to_rownames(var = "basin_name") %>% 
      select(survivalOffsprings) %>% 
      as.matrix() #%>% 
      # head() %>% is()
    
    # => Original version: calculate the proportion of active spawners
    # survivalOffsprings <- parameter$r * (spawnersTo^2 / (spawnersTo_50^2 + spawnersTo^2)) * spawnersTo
  } else {
    survivalOffsprings <- parameter$r * spawnersTo 
  }
```

**Comment by PMHLambert** [comment]
j'ai commencé à m'aventurer ... en commençant par me tromper de branche.  Il y a deux commit maladroits dans main :-( Je n'ai pas réussi à revenir en arrière. J'avoue ne pas avoir trop cherché de peur de faire plus de bêtises.
J'ai réussi à créer ma banche pour regarder le code. A moi l'aventure

**Comment by statnmap** [comment]
Ahlala !
Surtout, ne touches plus à rien dans _main_ ! Si c'est envoyé sur le serveur, on ne revient plus en arrière.
Peut-être qu'on peut empêcher l'envoi sur la branche _main_, mais je ne suis pas administrateur, alors je ne peux pas le faire moi-même.
Et il me faudrait quand même les droits pour que je puisse envoyer dans _main_ directement de mon côté si nécessaire
A voir avec @equinton ?

**Comment by equinton** [comment]
Bonjour,

Je viens de virer le droit d'admin à Patrick, et j'ai créé une 
protection sur la branche main. Sébastien, peux-tu me confirmer que tu 
peux toujours faire un commit ? Patrick, peux-tu vérifier que tu ne peux 
plus faire de bétises dans main ?

Merci,

Éric

**Comment by PMHLambert** [comment]
je peux continuer à faire des bêtises sur _main_ . J'en ai profité pour retirer ce que j'avais fait précédemment

**Comment by statnmap** [comment]
Traité dans https://github.com/inrae/diades.atlas/pull/126
