### ISSUE TITLE
UI refactoring

### ISSUE THREAD

**Issue by ColinFay** [inrae/diades.atlas#31]
- Change tab order

- Create some harmony between the tabs in terms of UI organisation

**Comment by ColinFay** [comment]
First draft of the UI : 

![draftui](https://user-images.githubusercontent.com/17936236/127132692-941a8415-cb07-46be-97fd-3f27d89aed52.png)

**Comment by ColinFay** [comment]
I just tried with the pop up and I'm not convinced after all. will try with a dropdown on hover.

![Screenshot 2021-07-28 at 10 34 32](https://user-images.githubusercontent.com/17936236/127292011-6b1fea26-008f-44e8-9f3b-75e0e82f670d.png)

**Comment by statnmap** [comment]
UI validée en réunion du 2021-11-26
