### ISSUE TITLE
[Rmd] Page 1 - Present distribution - Content

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#33]
- Combine occurrence at sea and abundance class in basins
- Filter on Species only

![image](https://user-images.githubusercontent.com/21193866/129003891-a188c16b-b0c8-4d4d-adb5-b25b22d105de.png)
![image](https://user-images.githubusercontent.com/21193866/129003937-4907cd66-1646-4709-bfc6-7bc77cbcee5f.png)

**Comment by statnmap** [comment]
- [ ] INRAE propose la requete SQL pour extraire ces données en mer (et qui prend switch (rectangle  or area) + id_espece en entrée) et sort la geom + occurence (chiffre).
- [ ] INRAE doit choisir si on présente la carte par rectangle ou par area sur l'UI
- [ ] INRAE propose la requete SQL pour extraire les données des bassins (et qui prend lang + id_espece en entrée) et sort la geom + les classes d'abondances traduites dans la langue + id_classe numérique pour savoir l'ordre (faible => forte)
- [ ] ThinkR doit indiquer le temps d'affichage pour savoir s'il est nécessaire d'avoir une géométrie simplifiée des 'area'

**Comment by statnmap** [comment]
- [ ] Bouton "Conservation status" => Une colonne dans la table
- [ ] Bouton "Source" => A retirer
- [ ] Bouton "Division / Rectangle" => Switch entre 2 modes de carte

**Comment by statnmap** [comment]
Code tmap pour les cartes: https://gitlab.irstea.fr/diades/diades.atlas.data/-/tree/master/scripts_R

**Comment by ColinFay** [comment]
Implémentation ok, une fois les PR associées mergées
