### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by ColinFay** [inrae/diades.atlas#38]
Possible deployment options: 

## ShinyProxy

+ every person needing to connect will have to open the front page, chose the app, and launch the container 

+ we can't optimise the session by preloading the db : every person connecting launches a container. If this container takes 15 seconds to launch, that's 15 second each. 

+ Multiple containers are needed (one for SP, one for the app).

+ ShinyProxy is a big "machine de guerre" that might be overkill if you don't have multiple apps and/or need a login mechanism

## Custome nginx + R 

+ There is an nginx on the front & multiple R sessions running the app. Nginx load-balances the users to these app. 

+ We can preload `n` R sessions, which will preload the datasets from the dataset

+ Multiple users can be on the same R session 

+ Only one container

**Comment by statnmap** [comment]
Discussion du 2021-11-26
Prod gérée côté INRAE: Livraison d'un conteneur Docker avec facilité de mise à jour
