### ISSUE TITLE
La liste des espèces est correcte dans le dropdown

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#41]

**Comment by ColinFay** [comment]
À réorganiser comme suit : 

> la liste des espèces est correcte mais pourrait être réorganisée comme suit (les aloses, les lamproies, les salmonidés, l'esturgeon et l'éperlan pour les anadromes, l'anguille, le mulet et le flet pour les catadromes)
c('Alosa alosa', 'Alosa fallax','Petromyzon marinus', 'Lampetra fluviatilis', 'Salmo salar', 'Salmo trutta', 'Acipenser sturio', 'Osmerus eperlanus', 'Anguilla anguilla', 'Chelon ramada', 'Platichthys flesus' )
