### ISSUE TITLE
Discussion : popups de la carte

### ISSUE THREAD

**Issue by ColinFay** [inrae/diades.atlas#49]
La carte affiche des popups quand on passe la souris sur des polygons : 

- "division" ou "rectangle" en mer 

![Screenshot 2021-11-17 at 16 52 32](https://user-images.githubusercontent.com/17936236/142234289-4ce59864-06a1-458c-b60a-f2d6c3e53fb0.png)

![Screenshot 2021-11-17 at 16 52 20](https://user-images.githubusercontent.com/17936236/142234295-e00810b7-2704-4684-a30c-7c9e30360385.png)

- Le numéro du bassin ou le nom du pays en terre 
- 
![Screenshot 2021-11-17 at 16 53 19](https://user-images.githubusercontent.com/17936236/142234433-962e332b-2063-4c17-bd1a-fd0dea847387.png)

![Screenshot 2021-11-17 at 16 53 23](https://user-images.githubusercontent.com/17936236/142234422-a0dd329c-1490-480a-a0a4-6e91ecb5c72f.png)

La carte affiche des popups quand on clique sur des polygons : 

- division / prévalence en mer
 
![Screenshot 2021-11-17 at 16 54 22](https://user-images.githubusercontent.com/17936236/142234641-4efff0b4-c680-495a-bc10-6900d0ca33e2.png)

![Screenshot 2021-11-17 at 16 54 30](https://user-images.githubusercontent.com/17936236/142234627-ecd3d5dc-4abe-435a-be54-fe43eb7f6750.png)

- numéro du bassin et interprétation, ou nom du pays
- 
![Screenshot 2021-11-17 at 16 55 40](https://user-images.githubusercontent.com/17936236/142234805-7c116bd1-d401-4838-bc1d-0b79e8081fec.png)

![Screenshot 2021-11-17 at 16 55 23](https://user-images.githubusercontent.com/17936236/142234822-7ce138c8-9f20-4546-aed6-79bcdbac0db3.png)

Quel comportement pour ces différents popups ? 

Je serais d'avis de les retirer, l'information et soit inutile, soit redondante avec la légende juste à côté.

**Comment by PMHLambert** [comment]
Il est inutile d'afficher le pays, le numéro des bassins versants
Il pourrait être par contre intéressant de visualiser dans les pop

- l'intitulé de la division ou du rectangle et la prévalence (et non la classe de prévalence) associée
- le nom du bassin versant et l'interprétation du statut des populations dans les bassins versants 
Cela permettrait une exploration plus approfondie de l'atlas, et des recherches en dehors de l'atlas

**Comment by statnmap** [comment]
Notez que comme c'est une traduction de tmap => leaflet, alors on n'est pas totalement maitre du contenu.  

- Les `hover`, quand on passe la souris, ne sont pas modifiable, ni supprimables (sauf en CSS dans l'app Shiny je suppose)
- Les `popup`, quand on clique, sont potentiellement modifiables en utilisant `popup.vars` comme paramètre dans la fonction d'affichage de la couhe: https://github.com/r-tmap/tmap/issues/570

Si vous voulez un traitement plus fin, alors il faut créer la carte directement en leaflet...

**Comment by PMHLambert** [comment]
Si je comprends bien, pour faire ce que j'imagine, il faut créer directement les cartes en leaflet. Donc probablement difficile à envisager  dans le temps imparti.  Supprimer les popup dans la version actuelle et garder l'idée pour une amélioration future (on travaille dur à son financement ;-)
