### ISSUE TITLE
Cannot select ecosystem

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#58]
Bug: Je ne peux pas sélectionner un ecosystème ici. Je suis en mode, je me balade sur la carte

![Capture d’écran de 2021-11-23 12-10-21](https://user-images.githubusercontent.com/21193866/143014205-5be13ea2-343d-419b-9408-1404b45ffbbb.png)

**Comment by ColinFay** [comment]
Vu et je suis dessus en réglant l'onglet 2. 

C'est à cause des pointer évent retirés dans le css.

**Comment by ColinFay** [comment]
closed via https://github.com/inrae/diades.atlas/commit/3a51fbdf002e76124eca076fa1f61e2e6e0b8816
