### ISSUE TITLE
[bug] If I click multiple time on the same row, it increases selection

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#59]
- This should not increase the number of items selected.
- Also maybe I would expect that click again on the same row would unselect the row.

![image](https://user-images.githubusercontent.com/21193866/143014763-49fd9841-5e6c-45b0-af42-2eb3683023d9.png)

**Comment by ColinFay** [comment]
Yep, saw that yesterday. Both are a WIP in the `issue_34` branch

**Comment by ColinFay** [comment]
closed via https://github.com/inrae/diades.atlas/commit/cbb71f9c1fbd2b6a02a91b91e45ee604e33b8d54
