### ISSUE TITLE
Setting up multilanguages help bubbles

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#6]
- [x] All different boxes of the interface (table, plots, drop-down menus ...) show a question mark circle (?) presenting an overlay help / explanation. 
- [x] The text inside the ovelay is HTML built from markdown syntax and is translated according to the language chosen on the interface.  
- [x] If there is no md file associated, the bubble does not appear. 
- [x] Propose a scheme for translations  
- [ ] ~Test how it can be combined with home page with d3js~

=> Optimize for Desktop use first.

Based on earlier project {prism} (ask Sébastien about it), I suggest a dedicated directory with md files and filename equivalent to the corresponding Shiny module name. Extension for translations can be mod_name.en.md, mod_name.fr.md, ...

**Comment by ColinFay** [comment]
Proto d'UI dans https://github.com/inrae/diades.atlas/tree/issue-6

https://user-images.githubusercontent.com/17936236/142491764-f0ba7f98-91c9-4718-b9d8-415cc0b4ce83.mp4

**Comment by statnmap** [comment]
@PMHLambert 
Merci de valider que tu retrouves bien les bulles d'aide sur les différentes pages où cela t'intéresse.
Bien sûr ce sera du texte à ajouter pour vous et on vous formera pour pouvoir le faire avec git / github.

Tu peux voir l'application ici: https://connect.thinkr.fr/diades-main/
Et tu peux passer la souris sur les (?) comme dans cette image:
![image](https://user-images.githubusercontent.com/21193866/144253084-36d11eed-7b08-48fd-a5a3-3ac8a435adcd.png)

**Comment by PMHLambert** [comment]
je vois bien les bulles d'aide qui apparaissent quand on passe la souris dessus. Je travaillerai demain pour préciser les bulles d'aide dont j'ai besoin
