### ISSUE TITLE
[4] Problème affichage dates

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#71]
Dans la branche issue-47, c'est ok, mais pas dans le 'main'.
Un problème de merge je pense.

main:
![image](https://user-images.githubusercontent.com/21193866/144263704-aa25853b-451f-4596-bd3d-591083db93e8.png)
issue-47
![image](https://user-images.githubusercontent.com/21193866/144263855-25652331-f983-4150-a2a1-f1c090aa1dcb.png)

- [ ] Ceci dit, à vérifier, mais il me semble qu'il ne faut choisir qu'une seule date et pas un range

_Originally posted by @statnmap in https://github.com/inrae/diades.atlas/issues/23#issuecomment-983758918_

**Comment by ColinFay** [comment]
J'ai oublié de faire le changement aussi sur cet onglet (je l'ai fait seulement sur le 3).
