### ISSUE TITLE
Add translations for l'espagnol et du portugais

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#78]
- [x] Data interne
- [x] Google Sheet

- [x] S'assurer que les instructions de mise à jour du docker sont ok pour qu'ils puissent reproduire la mise en prod si on n'est plus là
- [x] Remettre sur pieds le Connect
- [x] Bonus: Nous avons fait un Excel pour la traduction des bulles. Une ligne pour chaque page, une colonne pour chaque langue. Un script R pourrait lire et créer les fichiers md dans l'arborescence.

**Comment by ColinFay** [comment]
+ Data interne : je ne sais pas si tu parles des csv ou de la db postgre 
=> csv mis à jour dans #82 ainsi que les Rmd et le contenu de l'app. 
=> Certains points restent non traduits tant qu'on a pas la postgre à jour 

https://github.com/inrae/diades.atlas/blob/issue-78/R/utils_helpers.R#L28 => les utils helper de traduction renvoient de l'anglais tant que la postgre n'a pas les traduction

https://github.com/inrae/diades.atlas/blob/issue-78/dev/translation.Rmd#L106 => la traduction des status IUCN est aussi à faire dans la base postgre

+ Instructions de mise à jour du Docker, tout est là : https://gitlab.irstea.fr/diades/diades.atlas.deploy/-/blob/main/README.md

+ Connect de retour https://connect.thinkr.fr/diades-main/

+ En fait, on génère un csv depuis les contenus md, on va directement faire Google Sheet > csv  https://github.com/inrae/diades.atlas/blob/issue-78/dev/translation.Rmd#L48
