### ISSUE TITLE
Remplir et traduire les bulles d'aide

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#81]
- [x] Attendre le traitement de https://github.com/inrae/diades.atlas/issues/91 et les intsructions 
- [ ] Utiliser le csv pour traduire les bulles d'aide

**Comment by statnmap** [comment]
```
# catch_bycatch_help
# choose_a_daterange_help
# choose_a_scenario_help
# conservation_status_help
# define_anthropo_help
# map_abundance_help
# map_geometrie_help
# plot_evolution_help
# prediction_map_abundance_help
# prediction_plot_abundance_help
# run_simulation_help
# select_casestudy_help
# select_ecosystem_help
# show_results_help
# situation_table_help
# species_modal_help 
```

**Comment by statnmap** [comment]
[diades_bulles.xlsx](https://github.com/inrae/diades.atlas/files/7847263/diades_bulles.xlsx)

**Comment by ColinFay** [comment]
Je propose de ne pas faire de xlsx pour ne pas avoir à gérer les versions de fichier. 

J'ajoute un nouvel onglet dans le Google Sheet, pour être sûr qu'on travaille toujours sur la même version :)

**Comment by statnmap** [comment]
Bonjour Patrick,

Voici les fichiers csv à traduire.  
Les instructions de traduction les concernant seront sur la site web, sur la base de ce Rmd en cours de construction: https://github.com/inrae/diades.atlas/blob/111-bulles-aides/dev/translation.Rmd

Tu peux télécharger les fichiers, les modifier de ton côté, et les remettre ici dans un premier temps.  
Nous pourrons voir ensemble comment le faire avec github directement dans une branche pour les remettre dans le dossier "inst/".  

A noter:

+ Lire le csv avec un séparateur virgule `,` et avec l'option "Formater les champs entre guillemets comme texte"
+ Enregistrer le csv avec un séparateur virgule `,`

Les fichiers:

- [translation.csv](https://github.com/inrae/diades.atlas/files/8610067/translation.csv)
- [translation_help.csv](https://github.com/inrae/diades.atlas/files/8610068/translation_help.csv)
- [translation_iucn.csv](https://github.com/inrae/diades.atlas/files/8610069/translation_iucn.csv)

Bonne traduction

**Comment by PMHLambert** [comment]
voila les fichiers avec les bulles en français. Après vérifications dans l'appli, on les fera traduire pour 8 juin.

**Comment by PMHLambert** [comment]
Pour l'instant, il y a une bulle que je ne sais plus localisé : situation_table_help

**Comment by PMHLambert** [comment]
si possible, ne pas mettre la même bulle d'aide pour species_modal_help dans les onglets 1,2,3 et 4

**Comment by statnmap** [comment]
Merci de valider, quand l'application sera en production, que les traductions en portuguais sont fonctionnelles dans les titres notamment.

**Comment by statnmap** [comment]
Validé en réunion le 9/02/2023
