### ISSUE TITLE
Onglet 3 : colorisation de la carte "abondances dans les bessins versants" ou changemnt du titre de la carte

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#84]
Soit on maintient le titre, et les bassins versants doivent se colorisée en fonction de l'abondance pour l'année sélectionnée (avec une gestion de l'échelle de couleur)

soit la carte ne sert qu'à sélectionner le bassin versant et on change le titre

**Comment by statnmap** [comment]
Les couleurs sont mises à jour dans la dernière version.  
La gestion du titre va se faire avec l'issue: https://github.com/inrae/diades.atlas/issues/83
