### ISSUE TITLE
onglet 3: amélioration du rendu des resultats du modèle

### ISSUE THREAD

**Issue by PMHLambert** [inrae/diades.atlas#87]
L'idée est de faire une moyenne mobile pondérée des valeurs des 3 modèles ainsi qu'une enveloppe sous forme d'un ruban avec les valeur min et max des modèles

- [x] avec une correction du code pour tenir compte des besoins nouveaux requis pour la simulation online de HyDiaD
[atlas_visualisation_model.zip](https://github.com/inrae/diades.atlas/files/8332047/atlas_visualisation_model.zip)

**Comment by PMHLambert** [comment]
avec une correction du code pour tenir compte des besoins nouveaux requis pour la simulation online de HyDiaD
[atlas_visualisation_model.zip](https://github.com/inrae/diades.atlas/files/8332047/atlas_visualisation_model.zip)
D

**Comment by statnmap** [comment]
Dans cette partie de code, tu créés `label`, qui est utilisé pour colorer la courbe en fonction du croisement espece / BV.  
Cependant, on filtre les résultats sur l'espèce et le BV, cela signifie qu'il n'y aura qu'une seule ligne affichée sur le graphique.  
Par ailleurs, le sous-titre du graphique indique bien une espèce et un BV.  
Est-ce vraiment nécessaire d'ajouter cette variable ici ? 

```r
plot_hsi_nit_pl <- function(model_res,
                            selected_year,
                            selected_bv,
                            withNitStandardisation = FALSE) {
  
  model_res_filtered <- model_res %>%
    filter(basin_id == selected_bv) %>% 
    mutate(label = factor(paste(latin_name, basin_name, sep = ' in ')))
```

**Comment by statnmap** [comment]
Pour certaines espèces, le nit devient null. Par exemple pour l'alose.  
J'ai l'impression que les bornes min/max du modèle n'ont pas très bien fonctionné.
![image](https://user-images.githubusercontent.com/21193866/164443697-3fd99b32-c678-45d7-8434-7d7b6f2d15b6.png)

**Comment by PMHLambert** [comment]
Je pense que le problème vient des paramètres de simulation qui conduisent à des crach de population très/trop rapides. Pas un pb de calcul des bornes min et max. L'atlas va nous servir, dans un premier temps , à identifier ce type de problème !

**Comment by PMHLambert** [comment]
je valide
