### ISSUE TITLE
Suivi de l'utilisation de l'application

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#88]
- [ ] Faire un compte gmail pour le suivi ?
   - [x] Ajouté Patrick au compte Google Analytics: https://analytics.google.com
- [ ] atlas indexé sur Google : balise méta (og) sur l'app shiny pour que ce soit référencé par Google => Par ThinkR
- [x] Outil de suivi Google Analytics (ou Matomo: https://fr.matomo.org/pricing/)
- [ ] Outils de développeurs pour pouvoir suivre les visites et l'origine des rétroliens => Si on garde Google
- [ ] Définir les mots clé pour les rétroliens de référencement vers le site web => Par DiadES
- [ ] Définir les sites web partenaires où mettre les liens. => Par DiadES

**Comment by statnmap** [comment]
@equinton Avez vous un Matomo ou bien on reste sur Google Analytics?

**Comment by equinton** [comment]
Je me renseigne pour savoir si on a un serveur Matomo.

**Comment by statnmap** [comment]
Validé en réunion du 9/02/2023 qu'on reste sur Google Analytics.  
Patrick a les accès.
