### ISSUE TITLE
[4 - Future] UI

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#89]
- [x] Permettre une seconde entrée pour les mortalités (Avant 2050, Après 2050)
- [x] un truc qui dit que ça calcule
- [x] Dans l'onglet Futur, on reprend la meme chose que "Changement Climatique"
- [x] Choisir une date n'a de sens que quand on a lancé la simu, donc mettre après le lancer la simulation
- [ ] Mortalité anthropique doit commencer à zéro
- [-] Gestion du cache ? Ne pas faire de cache à cause des scénarios de mortalité, trop de combinaisons ? - non prioritaire

**Comment by PMHLambert** [comment]
Première version de la fonction qui lance une simulation HyDiaD. Nécessite probablement encore de l'optimisation
[HyDiaDsimulation.zip](https://github.com/inrae/diades.atlas/files/8332166/HyDiaDsimulation.zip)

**Comment by statnmap** [comment]
Traité dans https://github.com/inrae/diades.atlas/pull/126
