### ISSUE TITLE
Se séparer de Google Sheets

### ISSUE THREAD

**Issue by statnmap** [inrae/diades.atlas#91]
- [ ] Utiliser un fichier xls que l'utilisateur met dans le package plutôt que la connexion à Sheets. 
- [x] Mettre le fichier xls en gitignore ? ou faire des csv versionnés

> On n'a pas besoin de la fonctionnalité collaborative du remplissage des Google Sheets

**Comment by ColinFay** [comment]
Note : L'idée du Google Sheets était d'avoir un "single point of truth", ce qui évitera d'avoir un fichier Excel qu'on se balade par mail.

**Comment by equinton** [comment]
C'est juste au moment de la compilation qu'on récupère le fichier : l'édition collaborative peut exister ailleurs que dans Google Sheets.
Il suffit d'indiquer dans la doc que le fichier à télécharger depuis le site collaboratif est à placer à tel endroit, sous tel nom, et mettre ça en variable dans le script R.

**Comment by statnmap** [comment]
A valider dans cette nouvelle issue: https://github.com/inrae/diades.atlas/issues/69
